name: Build Kernel and Notify

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags
          fetch-depth: 0

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses6 libncurses-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libwxgtk3.2-dev lld

      - name: Run Build Script
        id: build
        run: set -o pipefail; bash build.sh 2>&1 | tee build.log

      - name: List files in workspace
        if: success()
        run: |
          # echo "Melihat isi direktori kerja untuk memastikan file zip ada:"
          ls -lA KernullException-*.zip

      - name: Send KSU Build
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ✅ *Build Selesai! (KernelSU)*
            Commit: `${{ github.sha }}`
          document: ./KernullException-KSU-*.zip
          format: markdown

      - name: Send Vanilla Build
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ✅ *Build Selesai! (Vanilla)*
            Commit: `${{ github.sha }}`
          document: ./KernullException-Vanilla-*.zip
          format: markdown

      - name: Send Failure Notification with Log
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message: |
            ❌ **Build Failed!** ❌

            The kernel compilation failed. See the attached log for details.
          document: ./build.log
          format: markdown
